services:
    app:
        build: .
        container_name: sakhai_app
        ports:
            - "8090:80"
        depends_on:
            - db
        env_file:
            - .env.docker
        volumes:
            - .:/var/www/html
    db:
        image: mysql:8
        container_name: sakhai_db
        restart: always
        environment:
            MYSQL_DATABASE: db_sakhai
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3390:3306"
